const faviconEl=document.querySelector('link[rel="icon"]')
const mediaQuery=window.matchMedia('(prefers-color-scheme: dark)')
mediaQuery.addEventListener('change',themeChange)
function themeChange(event){if(event.matches){faviconEl.setAttribute('href','favicon-dark.png')}else{faviconEl.setAttribute('href','favicon-light.png')}}
var Load=document.getElementById("Loading");var logoLoad=document.getElementById("logo-load");function loadfun(){Load.style.display="none";}
let openNav=function openNav(){document.getElementById("mySidenav").style.width="300px";}
let closeNav=function closeNav(){document.getElementById("mySidenav").style.width="0";}
const btnScrollTo=document.querySelector('.btn--scroll-to');const section1=document.querySelector('#section--1');btnScrollTo.addEventListener('click',function(e){const s1coords=section1.getBoundingClientRect();console.log(s1coords);console.log(e.target.getBoundingClientRect());console.log('Current scroll (X/Y)',window.pageXOffset,window.pageYOffset);console.log('height/width viewport',document.documentElement.clientHeight,document.documentElement.clientWidth);section1.scrollIntoView({behavior:'smooth'});});const nav=document.querySelector(".nav");const header=document.querySelector(".header");const navHeight=nav.getBoundingClientRect().height;const stickyNav=function(entries){const[entry]=entries;if(!entry.isIntersecting)nav.classList.add("sticky");else nav.classList.remove("sticky");};const headerObserver=new IntersectionObserver(stickyNav,{root:null,threshold:0,rootMargin:`-${navHeight}px`,});headerObserver.observe(header);window.onscroll=function(){myFunction();};var navbar=document.getElementById("navbar");var sticky=navbar.offsetTop;function myFunction(){if(window.pageYOffset>=sticky){navbar.classList.add("sticky");}else{navbar.classList.remove("sticky");}}
document.querySelector(".nav-link").addEventListener("click",function(e){e.preventDefault();if(e.target.classList.contains(".nav-link")){const id=e.target.getAttribute("href");document.querySelectorAll(id).scrollIntoView({behavior:"smooth"});}});var mybutton=document.getElementById("myBtn");window.onscroll=function(){scrollFunction();};function scrollFunction(){if(document.body.scrollTop>20||document.documentElement.scrollTop>20){mybutton.style.display="block";}else{mybutton.style.display="none";}}
function topFunction(){document.body.scrollTop=0;document.documentElement.scrollTop=0;}
$(".show-more").click(function(){if($(".text").hasClass("show-more-height")){$(this).text("(Show Less 👇)");}else{$(this).text("(Show More 👆)");}
$(".text").toggleClass("show-more-height");});